# primeiramente vamos dar um nome para o workflow (pipeline) no formato de pares chave: valor
name: Workflow
# agora vamos identificar alguns eventos (push e pull_request) do pipeline 
on:
  push: 
    branches:
      - main
  pull_request:
    branches:
      - main
      
# agora vamos incluir algumas tarefas
jobs:
  job1:
    name: Job 1
    runs-on: ubuntu.latest  # aqui é uma máquina virtual docker para rodar nossos passos nesta máquina
      
    steps:
    - name: Passo 1
      run: echo "Exibir uma mensagem de texto para o passo 1"

    - name: Passo 2
      run: echo "Exibir uma mensagem de texto para o passso 2"

  job2:
    name: Job 2
    runs-on: ubuntu.latest
    
    steps:
    - name: Passo 1
      run: echo "Exibir uma mensagem de texto do job 2 para o passo 1"
      
    - name: Passo 2
      run: echo "Exibir uma mensagem de texto do job 2 para o passso 2"
    
      
