# primeiramente vamos dar um nome para o workflow (pipeline) no formato de pares chave: valor
name: Workflow
# agora vamos identificar alguns eventos (push e pull_request) do pipeline 
on:
  push: 
    branches:
      - main
  pull_request:
    branches:
      - main
      
# agora vamos incluir algumas tarefas
jobs:
  job1:
    # incluindo o nome da tarefa Job 1
    name: Job 1
    # importante definir o ambiente (máquina virtual docker linux) onde iremos rodar nossos passos
    runs-on: ubuntu.latest  

    # dentro das tarefas podemos incluir um vetor de dois passos para exibir duas mensagens na console  
    steps:
    - name: Passo 1
      run: echo "Exibir uma mensagem de texto para o passo 1"

    - name: Passo 2
      run: echo "Exibir uma mensagem de texto para o passso 2"
      
  # vamos incluir mais outra tarefa similar, apenas para exemplificar a execução do pipeline
  job2:
    # incluindo o nome da tarefa Job 2
    name: Job 2
    runs-on: ubuntu.latest
    
    steps:
    - name: Passo 1
      run: echo "Exibir uma mensagem de texto do job 2 para o passo 1"
      
    - name: Passo 2
      run: echo "Exibir uma mensagem de texto do job 2 para o passso 2"
    
      
